development:
  DB_FILENAME: db/local/dev.db
  FOOD_API_TOKEN: ""
  SESSION_SECRET: ""
  REDISCLOUD_URL: "redis://:"
  DB_URL: "postgres://"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_REGION: "us-east-1"
  HANDLE_IMG_QUEUE: 
  HANDLE_IMG_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/..."
  R2_ACCESS_KEY_ID: ""
  R2_SECRET_ACCESS_KEY: ""
  CLOUDFLARE_R2_ID: ""

test:
  DB_FILENAME: db/local/test.db
  FOOD_API_TOKEN: ""
  SESSION_SECRET: ""
  REDISCLOUD_URL: ""
  DB_URL: "postgres://"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_REGION: "us-east-1"
  HANDLE_IMG_QUEUE: 
  HANDLE_IMG_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/..."
  R2_ACCESS_KEY_ID: ""
  R2_SECRET_ACCESS_KEY: ""
  CLOUDFLARE_R2_ID: ""

production:
  FOOD_API_TOKEN: ""
  SESSION_SECRET: ""
  REDISCLOUD_URL: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_REGION: "us-east-1"
  HANDLE_IMG_QUEUE: 
  HANDLE_IMG_QUEUE_URL: ""
  R2_ACCESS_KEY_ID: ""
  R2_SECRET_ACCESS_KEY: ""
  CLOUDFLARE_R2_ID: ""
